---
title: "LAGOSNE_Metadata"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Information About the LAGOSNE Dataset

The Lake Multi-Scaled Geospatial and Temporal Database (LAGOSNE) is a collection of several data modules that contain information on lakes in the northern United States. The modules contain data from thousands of lakes in 17 states in the northeastern and midwestern United States, from Missouri to Maine. The dataset includes a complete list of all lakes bigger than 4 hectacres in the 17 state area, and water quality data on a large number of lakes, spanning every state. The purpose of collecting this data in one place is to facilitate the continued understanding of water quality in these lakes through open-source access. More information about the general composition of the LAGOSNE dataset can be found at

https://cont-limno.github.io/LAGOSNE/articles/lagosne_structure.html


## Information About the Minnesota Ecoregions Shapefile

Ecoregions are developed by the US Environmental Protection Agency and are used by planning managers to understand the type of land use that occurs in different regions of the United States. There are different levels of ecoregions. Level I has low resolution, and divides North America into 15 ecological regions, while Level IV offers fine ecological resolution for each state. This data was published by the U.S. EPA Office of Research and Development (ORD) - National Health and Environmental Effects Research Laboratory (NHEERL). Minnesota contains parts of three distinct Level II ecoregions. We selected Level II ecoregions for our project. This level of resolution allows us to broadly capture the natural ecosystem variation in different parts of the state in our statistical models. We did not use Level III ecoregions because not every Level III ecoregion contained enough water quality data.

The following information is copied directly from the EPA's metadata page about the Minnesota Level II ecoregions: 

"Originator: U.S. Environmental Protection Agency
Publication_Date: 20100501
Title: NA_CEC_Eco_Level2
Geospatial_Data_Presentation_Form: vector digital data
Series_Information:
Publication_Information:
Publication_Place: Corvallis, OR
Publisher:
U.S. EPA Office of Research & Development (ORD) - National Health and Environmental Effects Research Laboratory (NHEERL)
Online_Linkage: <ftp://ftp.epa.gov/wed/ecoregions/cec_na/NA_CEC_Eco_Level2.zip>"


## Information About the Creation of Our Master Raw Dataframe

The LAGOSNE dataset contains hundreds of variables on water quality, many of which are not relevant or pertinent to our specific research questions. In addition, our questions are limited to the state of Minnesota. Therefore, we wrangled the entire LAGOSNE dataset to create a master raw dataframe from which we would answer our research questions. For more information about which variables we chose, see the next section in our metadata file.

We joined our LAGOSNE sub-dataset with our Level II Ecoregions shapefile so our master dataset reflects which ecoregion each lake in our study is located. 


## Information About The Variables In Our Master Raw Dataframe

We selected only the variables that we need to answer our research questions. They are as follows:

###Dependent Variables: 
* Secchi Depth (m): This variable measures the visibility of the water column, by using a secchi disk. Its units are meters. Along with Chlorophyll a concentration, secchi depth is one of two dependent variables in our study; we are considering it a proxy of land use. We will be using it to test research questions 1+2.

* Chlorophyll a (mg/L): This variable measures the Chlorophyll a concentration in a water quality sample. Its units are mg/L. Along with secchi depth, Chlorophyll a concentration is one of two dependent variables in our study; we are considering it a proxy of land use. We will be using it to test research questions 1+2.

###Independent Variables:
We are testing our hypotheses surrounding varying land use by comparing nitrogen and phosphorus concentrations by land use/land cover. We are using 2011 USGS land use/land cover information as it is listed in LAGOSNE. For more information about the USGS's 2011 classification scheme, visit

https://www.mrlc.gov/data/legends/national-land-cover-database-2011-nlcd2011-legend


The raw list of land cover from the LAGOSNE dataset is as follows: 

* No data
* Open Water
* "Residential, low intensity"
* "Developed, open space."
* "Residential, high intensity"
* "Developed, low intensity. "
* Commercial/industrial/transportation
* "Developed, medium intensity."
* "Developed, high Intensity. "
* Bare rock/sand/clay
* Quarries/strip mines/gravel pits 
* Transitional (barren) 
* Deciduous forest
* Evergreen forest
* Mixed forest
* Shrubland 
* Scrub/shrub
* Orchards/vineyards
* Grasslands/herbaceous
* Pasture/hay
* Row crops
* Small grains 
* Urban/recreational grasses 
* "Woody wetlands. Note, this variable not calculated in 1992"
* Woody wetlands 
* Emergent herbaceous wetlands 
* Emergent herbaceous wetlands


We did some simplification of land use to focus on land uses we expect will have relationships with secchi depth and Chlorophyll a concentration. For example, we combined "Developed, Medium Intensity" and "Developed High Intensity" into an "Intense Urban" land use cover. All of these variables are independent variables in our study and will be used to test research questions one and two. Not all land uses were used in our study.

* Intense Urban: Contains "Developed, medium intensity", "Developed, high Intensity"
* Open Urban: Contains "Developed, open space"
* Barren: Contains Bare rock/sand/clay
* Forest: Contains Deciduous forest, Evergreen forest, Mixed forest
* Grass/shrub: Contains Scrub/shrub, Grasslands/herbaceous
* Pasture: Contains Pasture/hay
* Row crops: Contains Row crops 
* Wetlands: Contains Woody wetlands , Emergent herbaceous wetlands


In addition, our master raw dataset contains the following three independent variables:

* EPA Level II Ecoregion: From the EPA Level II Ecoregion shapefile. This will be used to test questions one and two.
* Season of data collection: Early (May 15 and Before), Prime (May 16 - September 30), and Late (October 1 and later). These season designations are somewhat arbitrary, but are based off of our prior knowledge of when the prime biological growing season is in Minnesota.
* Lake IWS Ratio: The ratio of lake size to watershed size

Ecoregions will allow us to account for natural land use and climatological variation across the state of Minnesota. Dividing our data into arbitrary but approximate delineations of when the prime growing season occurs in Minnesota will allow us to test for seasonality in our data analysis. The Lake IWS ratio is an important variable to keep track of because lake to watershed ratio may affect water quality.