---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Impacts of Land Use on Water Quality in Minnesota"
subtitle: "https://github.com/lhr12/HDA_Project"
author: "Keith Bollt, Jake Greif, Felipe Raby-Amadori, & Lindsay Roth"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage

<Arrow brackets are used for annotating the RMarkdown files. Text within these brackets should not appear in the final version of the PDF document>

<**General Guidelines**>
<1. Write in scientific style> 
<2. [Global options for R chunks](https://rmarkdown.rstudio.com/lesson-3.html) should be set so that only relevant output is displayed>
<3. Make sure your final knitted PDF looks professional. Format tables appropriately, size figures appropriately, make sure bulleted and numbered lists appear as such, avoid awkwardly placed page breaks, etc.>

```{r setup, include=FALSE}
# Set your working directory
getwd()

# Load your packages
suppressMessages(library(tidyverse))
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(viridis)
library(knitr)
library(lubridate)
library(lme4)
library(nlme)
library(trend)
library(gridExtra)
library(corrplot)
library(car)
library(bestNormalize)
library(stats)
library(LAGOSNE)
library(sf)
library(maps)
library(mapview)
library(lme4)

# Set your ggplot theme
theme_set(theme_classic())

# Load your datasets
#Early
LAGOS.MN.processed.Early <- read.csv("./data/processed/LAGOS.MN.processed.Early.csv")
#Late
LAGOS.MN.processed.Late <-read.csv("./data/processed/LAGOS.MN.processed.Late.csv")
#Prime
LAGOS.MN.processed.Prime <-read.csv("./data/processed/LAGOS.MN.processed.Prime.csv")
```


# Rationale and Research Questions

<Write 1-2 paragraph(s) detailing the rationale for your study. This should include both the context of the topic as well as a rationale for your choice of dataset (reason for location, variables, etc.) A few citations should be included to give context for your topic. You may choose to configure autoreferencing for your citations or add these manually.>

<At the end of your rationale, introduce a numbered list of your questions (or an overarching question and sub-questions). Each question should be accompanied by one or more working hypotheses, inserted beneath each question.>

Land use has a large impact on nutrient runoff into streams, lakes, and other water bodies. Understanding the causes of nutrient problems will better inform management strategies. A study looking at land use and water quality in the Chaohu Basin in China found that forest and grassland has a statistically significant negative correlation with water quality, while urbanization has a statistically significant positive correlation with water quality and farmland has a more complex relationship (Huang et al., 2013). We applied some of the basic research questions of the Huang et al. study to the United States. Nutrient management has been a challenge for states in the effort to control harmful algal blooms and coastal dead zones (Wurtsbaugh et al., 2019). We selected the state of Minnesota for our study because Minnesota has wide variety of land uses.  It includes a large urban center (the Twin Cities metropolitan area), natural lands in the northern part of the state, and large agricultural areas. It also has a large number of lakes with water quality sampling. In addition, studies performed in Minnesota have shown that water quality has been adversely affected by land use changes (Christensen et al., 2012); (Maalim et al., 2013). There may also be seasonal relationships between water quality and land use; for example, we know that farmers apply nutrients at certain times of year and lakes naturally have higher levels of algae in summer months.
* * 
Research Questions:
	In order to evaluate the relationship between land use wand lacustrine water quality in the state of Minnesota, we asked the following two questions to help guide our research:
1.	What are the predictors of nutrients based on land use in watersheds in the state of Minnesota?
Hypothesis 1a: The percentage of urbanized land in a lake’s watershed in the state of Minnesota will have a statistically significant negative effect on water quality, as measured by higher Chlorophyll a concentrations and lower secchi depth measurements.
Hypothesis 1b: The percentage of agricultural land in a lake’s watershed in the state of Minnesota will have a statistically significant negative effect on water quality, as measured by higher Chlorophyll a concentrations and lower secchi depth measurements.
2.	How do you characterize seasonal variation between the predictors of nutrients?
Hypothesis 2: The water quality in Minnesota lakes will demonstrate a statistically significant seasonal pattern.

Goals:
	By testing our hypotheses, we aim to accomplish the following goals:
1.	Determine how land use, watershed size, and ecoregion explain variation in nutrient loading indicators.
2.	Discern whether there a seasonal trends in nutrient loading indicators based on land use types, watershed size, and ecoregion.
3.	Provide insight to inform decisions about nutrient management practices based on land use types, watershed size, and ecoregion.


\newpage

# Dataset Information

<Provide information on how the dataset for this analysis were collected, the data contained in the dataset, and any important pieces of information that are relevant to your analyses. This section should contain much of same information as the metadata file for the dataset but formatted in a way that is more narrative.>

<Describe how your team wrangled your dataset in a format similar to a methods section of a journal article.>

<Add a table that summarizes your data structure (variables, units, ranges and/or central tendencies, data source if multiple are used, etc.). This table can be made in markdown text or inserted as a `kable` function in an R chunk. If the latter, do not include the code used to generate your table.>

\newpage

# Exploratory Analysis 

<Insert exploratory visualizations of your dataset. This may include, but is not limited to, graphs illustrating the distributions of variables of interest and/or maps of the spatial context of your dataset. Format your R chunks so that graphs are displayed but code is not displayed. Accompany these graphs with text sections that describe the visualizations and provide context for further analyses.>

<Each figure should be accompanied by a caption, and each figure should be referenced within the text>

\newpage

# Analysis

<Insert visualizations and text describing your main analyses. Format your R chunks so that graphs are displayed but code and other output is not displayed. Instead, describe the results of any statistical tests in the main text (e.g., "Variable x was significantly different among y groups (ANOVA; df = 300, F = 5.55, p < 0.0001)"). Each paragraph, accompanied by one or more visualizations, should describe the major findings and how they relate to the question and hypotheses. Divide this section into subsections, one for each research question.>

<Each figure should be accompanied by a caption, and each figure should be referenced within the text>

## Question 1: <insert specific question here and add additional subsections for additional questions below>

## Question 2: 




\newpage

# Summary and Conclusions
<Summarize your major findings from your analyses in a few paragraphs. What conclusions do you draw from your findings? Relate your findings back to the original research questions and rationale.>

\newpage

# References
<add references here> 
Christensen, Victoria G., et al. "Relations between Retired Agricultural Land, Water Quality, and	Aquatic-Community Health, Minnesota River Basin." Journal of Environmental Quality,	vol. 41, no. 5, 2012, pp. 1459-72. ProQuest,	https://login.proxy.lib.duke.edu/login?url=https://search.proquest.com/docview/1	95114913?accountid=10598.

Maalim, Fukhrudin K., Melesse, Assefa M., Belmont, Patrick., Gran, Karen B. "Modeling the	impact of land use changes on runoff and sediment yield in the Le Sueur watershed,	Minnesota using GeoWEPP." CATENA Volume 107, 2013, Pages 35	45, https://doi.org/10.1016/j.catena.2013.03.004.

Huang, J., Zhan, J., Yan, H., Wu, F., Xiangzheng Deng, X. “Evaluation of the Impacts of Land	Use on Water Quality: A Case Study in The Chaohu Lake Basin,” The Scientific World	Journal, vol. 2013, Article ID 329187, 7 pages,	2013. https://doi.org/10.1155/2013/329187.

Ramstack, Joy M., Sherilyn C. Fritz, and Daniel R. Engstrom. "Twentieth Century Water Quality	Trends	in Minnesota Lakes Compared with Presettlement Variability." Canadian Journal	of Fisheries and Aquatic Sciences, vol. 61, no. 4, 2004, pp. 561-576.	ProQuest, https://login.proxy.lib.duke.edu/login?url=https://search.proquest.com/docvi	ew/29317301?accountid=10598.

Wurtsbaugh, WA, Paerl, HW, Dodds, WK. “Nutrients, eutrophication and harmful algal blooms	along the freshwater to marine continuum.” WIREs	Water. 2019; 6:e1373. https://doi.org/10.1002/wat2.1373

