---
title: "Final_Wrangling_Doc"
author: "BGRR"
date: "11/11/2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Setup_Load_Data}
getwd()

#load packages
library(tidyverse)
library(lubridate)
library(LAGOSNE)
library(sf)
library(maps)
library(mapview)

#load LAGOS data
LAGOSdata <- lagosne_load()

# creating specific lagos files
LAGOSstate <- LAGOSdata$state
LAGOSlocus <- LAGOSdata$locus
LAGOSnutrient <- LAGOSdata$epi_nutr
LAGOSiwslulc <- LAGOSdata$iws.lulc
LAGOSiws <- LAGOSdata$iws

theme_set(theme_classic())
```

```{r MN_Nutrient_Data}
#checking each state for nutrient data

#State 14: Minnesota
LAGOSlocus.MN <- LAGOSlocus %>% filter (state_zoneid == "State_14")
LAGOSnutrient.MN <- LAGOSlocus.MN %>%
  left_join(LAGOSnutrient, by = "lagoslakeid") 
```

```{r Joining_MN_Nutrient_lulc}
#getting the area of the iws
LAGOSiws.area <- select(LAGOSiws, "lagoslakeid", "iws_ha")


#joining MN locus with iwslulc and adding the area of IWS
LAGOSiws.MN <- LAGOSlocus.MN %>% 
  left_join(LAGOSiwslulc, by = "lagoslakeid") %>%
  left_join(LAGOSiws.area, by = "lagoslakeid")

##selecting 2011 lulc
LAGOSiws2011.MN <- LAGOSiws.MN %>% 
  select(lagoslakeid,state_zoneid, lake_area_ha, iws_ha,
         iws_nlcd2011_pct_11, iws_nlcd2011_pct_21, iws_nlcd2011_pct_22,
         iws_nlcd2011_pct_23, iws_nlcd2011_pct_24, iws_nlcd2011_pct_31,
         iws_nlcd2011_pct_41, iws_nlcd2011_pct_42, iws_nlcd2011_pct_43,
         iws_nlcd2011_pct_52, iws_nlcd2011_pct_71, iws_nlcd2011_pct_81,
         iws_nlcd2011_pct_82, iws_nlcd2011_pct_90, iws_nlcd2011_pct_95)
```

```{r, Filter_Nutrient_Dates}
#filtering state nutrient data #FRA. We can expand this range
LAGOSnutrient.MN.skinny <- LAGOSnutrient.MN %>%
  filter(sampledate > "2008-12-31" & sampledate < "2015-01-01")

# sapply(LAGOSnutrient.MN.skinny, summary)
```

```{r, Joined_MN_df}
##Joining iws.lulc and nutrient
LAGOSiws.nutrient.2011.MN <-  left_join(LAGOSnutrient.MN.skinny,
                                        LAGOSiws2011.MN, by =
                                          c("lagoslakeid", "lake_area_ha")) 

LAGOSiws.nutrient.2011.MN <- LAGOSiws.nutrient.2011.MN %>%
  select(lagoslakeid, nhd_lat, nhd_long, lake_area_ha, lake_perim_meters,
         iws_zoneid, iws_ha, state_zoneid.x, elevation_m, sampledate, chla,secchi, 
         iws_nlcd2011_pct_11, iws_nlcd2011_pct_21, iws_nlcd2011_pct_22, 
         iws_nlcd2011_pct_23, iws_nlcd2011_pct_24, iws_nlcd2011_pct_31, 
         iws_nlcd2011_pct_41, iws_nlcd2011_pct_42, iws_nlcd2011_pct_43, 
         iws_nlcd2011_pct_52, iws_nlcd2011_pct_71, iws_nlcd2011_pct_81, 
         iws_nlcd2011_pct_82, iws_nlcd2011_pct_90, iws_nlcd2011_pct_95)

# sapply(LAGOSiws.nutrient.2011.MN, summary)
```

```{r, Visualize_data, eval = FALSE}
# Looking at the data

ggplot(LAGOSiws.nutrient.2011.MN, aes(x = sampledate, y = secchi, color = lagoslakeid)) +
  scale_color_viridis_c(option = "plasma") +
  geom_line() 

ggplot(LAGOSiws.nutrient.2011.MN, aes(x = sampledate, y = chla, color = lagoslakeid)) +
  scale_color_viridis_c(option = "plasma") +
  geom_line() 



```

```{r Create_Full_df}
LAGOS.MN.processed <- LAGOSiws.nutrient.2011.MN %>%
  mutate(IntenseUrban.pct = iws_nlcd2011_pct_23 + iws_nlcd2011_pct_24,
         OpenUrban.pct = iws_nlcd2011_pct_21,
         Barren.pct = iws_nlcd2011_pct_31,
         Forest.pct = iws_nlcd2011_pct_41 + iws_nlcd2011_pct_42 + iws_nlcd2011_pct_43,
         GrassShrub.pct = iws_nlcd2011_pct_52 + iws_nlcd2011_pct_71,
         Wetland.pct = iws_nlcd2011_pct_90 + iws_nlcd2011_pct_95,
         Pasture.pct =  iws_nlcd2011_pct_81,
         RowCrop.pct = iws_nlcd2011_pct_82) %>%
  select(-c(iws_nlcd2011_pct_11, iws_nlcd2011_pct_21, iws_nlcd2011_pct_22, 
            iws_nlcd2011_pct_23, iws_nlcd2011_pct_24, iws_nlcd2011_pct_31, 
            iws_nlcd2011_pct_41, iws_nlcd2011_pct_42, iws_nlcd2011_pct_43, 
            iws_nlcd2011_pct_52, iws_nlcd2011_pct_71, iws_nlcd2011_pct_81, 
            iws_nlcd2011_pct_82, iws_nlcd2011_pct_90, iws_nlcd2011_pct_95)) %>%
  na.omit() %>%
  mutate(LakeIWS.Ratio = lake_area_ha/iws_ha) %>%
  mutate(DOY = yday(sampledate))
  
# sapply(LAGOS.MN.processed, summary)
```

```{r adding a season column}
#We are creating growing seasons; early, prime, late. They will be based off of water temperature and day of year. We choose May 15 and October 1 because these are arbitrary but approximate bookends to the prime growing season.

LAGOS.MN.processed$EarlyTrue <- LAGOS.MN.processed$DOY < 136 #Before May 15
LAGOS.MN.processed$PrimeTrue <- LAGOS.MN.processed$DOY >=136 & LAGOS.MN.processed$DOY <= 273 #May 15 to September 30
LAGOS.MN.processed$LateTrue <- LAGOS.MN.processed$DOY > 273  #October 1 and later

LAGOS.MN.processed$EarlyTrue <- ifelse(LAGOS.MN.processed$EarlyTrue == TRUE, "Early", "No")
LAGOS.MN.processed$PrimeTrue <- ifelse(LAGOS.MN.processed$PrimeTrue == TRUE, "Prime", "No")
LAGOS.MN.processed$LateTrue <- ifelse(LAGOS.MN.processed$LateTrue == TRUE, "Late", "No")

LAGOS.MN.processed$Season <- LAGOS.MN.processed$EarlyTrue == "Early"
  
LAGOS.MN.processed$Season[LAGOS.MN.processed$EarlyTrue == "Early"] <- "Early"
LAGOS.MN.processed$Season[LAGOS.MN.processed$PrimeTrue == "Prime"] <- "Prime"
LAGOS.MN.processed$Season[LAGOS.MN.processed$LateTrue == "Late"] <- "Late"

LAGOS.MN.processed  <- LAGOS.MN.processed %>%
  select(-c(EarlyTrue, PrimeTrue, LateTrue))
```

```{r Adding_Ecoregions2}
LAGOS.MN.processed.sf <- st_as_sf(LAGOS.MN.processed, coords = c("nhd_long", "nhd_lat"), crs = 4326)

LAGOS.MN.processed.UTM.sf <- st_transform(LAGOS.MN.processed.sf, crs=32615)

#Loading US Ecoregions Level II
US.Ecoregions.sf <- st_read('./Data/Raw/NA_CEC_Eco_Level2.shp')

US.Ecoregions.sf_UTM <- st_transform(US.Ecoregions.sf, crs=32615) 


#Loading the MN state boundary  
# generate a map of U.S. states
states <- st_as_sf(map(database = "state", plot = FALSE, fill = TRUE, col = "white"))

# filter MN
states.MN <- filter(states, ID %in%
c("minnesota"))

states.MN_UTM <- st_transform(states.MN, crs=32615) 

#Ecoregions level II for Minnesota
MN.Ecoregions.sf_UTM <- st_intersection(US.Ecoregions.sf_UTM, states.MN_UTM)

#Selecting level 2 ecoregions names
MN.Ecoregions.sf_UTM <- select(MN.Ecoregions.sf_UTM, NA_L2NAME)
colnames(MN.Ecoregions.sf_UTM)[1] <- "Ecoregion"

LAGOS.MN.processed.sf <- st_join(LAGOS.MN.processed.UTM.sf, MN.Ecoregions.sf_UTM)
LAGOS.MN.processed.sf <- na.omit(LAGOS.MN.processed.sf)

```

```{r Creating_Seasons_dfs}
#Creating sf seasons files
LAGOS.MN.processed.Early.sf <- filter(LAGOS.MN.processed.sf, Season == "Early")
LAGOS.MN.processed.Prime.sf <- filter(LAGOS.MN.processed.sf, Season == "Prime")
LAGOS.MN.processed.Late.sf <- filter(LAGOS.MN.processed.sf, Season == "Late")

#Creating regular season files (doesn't have ecoregions column)
LAGOS.MN.processed.Early <- filter(LAGOS.MN.processed, Season == "Early")
LAGOS.MN.processed.Prime <- filter(LAGOS.MN.processed, Season == "Prime")
LAGOS.MN.processed.Late <- filter(LAGOS.MN.processed, Season == "Late")


#To look at the statistics
summary(LAGOS.MN.processed.Early.sf$chla)
summary(LAGOS.MN.processed.Prime.sf$chla)
summary(LAGOS.MN.processed.Late.sf$chla)

summary(LAGOS.MN.processed.Early.sf$secchi)
summary(LAGOS.MN.processed.Prime.sf$secchi)
summary(LAGOS.MN.processed.Late.sf$secchi)


```

```{r scatterplots, eval = FALSE}
#Exploring some preliminary trends for Late Season (Highest Mean Chla and Lowest Mean Secchi Depth)

ggplot(LAGOS.MN.processed.Late.sf, aes(x = IntenseUrban.pct, y = secchi)) +
geom_point() +
geom_smooth(method=lm, se=FALSE) +
xlab(expression("% Intense Urban")) +
ylab(expression("Secchi Depth (m)")) +
ggtitle("% Intense Urban vs Secchi Depth Scatterplot, Late Season") +
theme(plot.title = element_text(hjust = 0.5))

ggplot(LAGOS.MN.processed.Late.sf, aes(x = Forest.pct, y = secchi)) +
geom_point() +
geom_smooth(method=lm, se=FALSE) +
xlab(expression("% Forest")) +
ylab(expression("Secchi Depth (m)")) +
ggtitle("% Forest vs Secchi Depth Scatterplot, Late Season") +
theme(plot.title = element_text(hjust = 0.5))

ggplot(LAGOS.MN.processed.Late.sf, aes(x = RowCrop.pct, y = secchi)) +
geom_point() +
geom_smooth(method=lm, se=FALSE) +
xlab(expression("% Row Crops")) +
ylab(expression("Secchi Depth (m)")) +
ggtitle("% Row Crops vs Secchi Depth Scatterplot, Late Season") +
theme(plot.title = element_text(hjust = 0.5))

ggplot(LAGOS.MN.processed.Late.sf, aes(x = IntenseUrban.pct, y = chla)) +
geom_point() +
geom_smooth(method=lm, se=FALSE) +
xlab(expression("% Intense Urban")) +
ylab(expression("chla (mg/L)")) +
ggtitle("% Intense Urban vs Chla Scatterplot, Late Season") +
theme(plot.title = element_text(hjust = 0.5))

ggplot(LAGOS.MN.processed.Late.sf, aes(x = Forest.pct, y = chla)) +
geom_point() +
geom_smooth(method=lm, se=FALSE) +
xlab(expression("% Forest")) +
ylab(expression("chla (mg/L)")) +
ggtitle("% Forest vs Chla Scatterplot, Late Season") +
theme(plot.title = element_text(hjust = 0.5))

ggplot(LAGOS.MN.processed.Late.sf, aes(x = RowCrop.pct, y = chla)) +
geom_point() +
geom_smooth(method=lm, se=FALSE) +
xlab(expression("% Row Crops")) +
ylab(expression("chla (mg/L)")) +
ggtitle("% Row Crops vs Chla Scatterplot, Late Season") +
theme(plot.title = element_text(hjust = 0.5))
```

FRA Comment: Next plot main purpose is to check is we have enough data in each ecoregion.

```{r summary.for.early.season, eval = TRUE}
LAGOS.MN.Summary.Early <- LAGOS.MN.processed.Early %>%
group_by(lagoslakeid) %>%
summarise(secchi.mean = mean(secchi),
          chla.mean = mean(chla),
          LakeIWS.Ratio = mean(LakeIWS.Ratio),
          IntenseUrban.pct = mean(IntenseUrban.pct),
          OpenUrban.pct = mean(OpenUrban.pct),
          Barren.pct = mean(Barren.pct),
          Forest.pct = mean(Forest.pct),
          GrassShrub.pct = mean(GrassShrub.pct),
          Wetland.pct = mean(Wetland.pct),
          Pasture.pct = mean(Pasture.pct),
          RowCrop.pct = mean(RowCrop.pct),
          Lat = mean(nhd_lat),
          Long = mean(nhd_long)
          ) %>%
  drop_na()

#Creating a MN.Ecoregions.sf_UTM variable without water (just for visualization)

MN.Ecoregions.sf_UTM_plot <- MN.Ecoregions.sf_UTM %>% 
  filter(Ecoregion != "WATER")

#SF file with the summary
LAGOS.MN.Summary.Early.sf <- st_as_sf(LAGOS.MN.Summary.Early, coords = c("Long", "Lat"), crs = 4326)

Early.MN <- ggplot() +
  geom_sf(data = MN.Ecoregions.sf_UTM_plot, aes(fill = Ecoregion)) +
  geom_sf(data = LAGOS.MN.Summary.Early.sf,
          alpha = 0.4, show.legend = "point") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(Early.MN)

```

```{r summary.for.prime.season, eval = TRUE}
LAGOS.MN.Summary.Prime <- LAGOS.MN.processed.Prime %>%
group_by(lagoslakeid) %>%
summarise(secchi.mean = mean(secchi),
          chla.mean = mean(chla),
          LakeIWS.Ratio = mean(LakeIWS.Ratio),
          IntenseUrban.pct = mean(IntenseUrban.pct),
          OpenUrban.pct = mean(OpenUrban.pct),
          Barren.pct = mean(Barren.pct),
          Forest.pct = mean(Forest.pct),
          GrassShrub.pct = mean(GrassShrub.pct),
          Wetland.pct = mean(Wetland.pct),
          Pasture.pct = mean(Pasture.pct),
          RowCrop.pct = mean(RowCrop.pct),
          Lat = mean(nhd_lat),
          Long = mean(nhd_long)
          ) %>%
  drop_na()

#SF file with the summary
LAGOS.MN.Summary.Prime.sf <- st_as_sf(LAGOS.MN.Summary.Prime, coords = c("Long", "Lat"), crs = 4326)

Prime.MN <- ggplot() +
  geom_sf(data = MN.Ecoregions.sf_UTM_plot, aes(fill = Ecoregion)) +
  geom_sf(data = LAGOS.MN.Summary.Prime.sf, 
          alpha = 0.4, show.legend = "point") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(Prime.MN)
```

```{r summary.for.late.season, eval = TRUE}
LAGOS.MN.Summary.Late <- LAGOS.MN.processed.Late %>%
group_by(lagoslakeid) %>%
summarise(secchi.mean = mean(secchi),
          chla.mean = mean(chla),
          LakeIWS.Ratio = mean(LakeIWS.Ratio),
          IntenseUrban.pct = mean(IntenseUrban.pct),
          OpenUrban.pct = mean(OpenUrban.pct),
          Barren.pct = mean(Barren.pct),
          Forest.pct = mean(Forest.pct),
          GrassShrub.pct = mean(GrassShrub.pct),
          Wetland.pct = mean(Wetland.pct),
          Pasture.pct = mean(Pasture.pct),
          RowCrop.pct = mean(RowCrop.pct),
          Lat = mean(nhd_lat),
          Long = mean(nhd_long)
          ) %>%
  drop_na()

#SF file with the summary
LAGOS.MN.Summary.Late.sf <- st_as_sf(LAGOS.MN.Summary.Late, coords = c("Long", "Lat"), crs = 4326)

Late.MN <- ggplot() +
  geom_sf(data = MN.Ecoregions.sf_UTM_plot, aes(fill = Ecoregion)) +
  geom_sf(data = LAGOS.MN.Summary.Late.sf, 
          alpha = 0.4, show.legend = "point") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(Late.MN)

```











FRA Comment: The next plot where the one we did for the proposal. We have to see if we want them



```{r summary.for.late.season, eval = FALSE}
secchiplot2.Late.MN <- ggplot() +
  geom_sf(data = states.MN, fill = "white") +
  geom_sf(data = LAGOS.MN.Summary.Late.sf, 
          aes(size = Urban.pct, color = secchi.mean),
          alpha = 0.4, show.legend = "point") +
  scale_color_viridis_c(option = "inferno") +
  labs(color = "Average \n Secchi \n Depth (m)", 
       size = "Urban \n Area \n %") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(secchiplot2.Late.MN)

secchiplot3.Late.MN <- ggplot() +
  geom_sf(data = states.MN, fill = "white") +
  geom_sf(data = LAGOS.MN.Summary.Late.sf, 
          aes(size = Ag.pct, color = secchi.mean),
          alpha = 0.4, show.legend = "point") +
  scale_color_viridis_c(option = "inferno") +
  labs(color = "Average \n Secchi \n Depth (m)", 
       size = "Agricultural \n Area \n %") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(secchiplot3.Late.MN)




chlaplot1.Late.MN <- ggplot() +
  geom_sf(data = states.MN, fill = "white") +
  geom_sf(data = LAGOS.MN.Summary.Late.sf, 
          aes(size = Undeveloped.pct, color = chla.mean),
          alpha = 0.4, show.legend = "point") +
  scale_color_viridis_c(option = "inferno") +
  labs(color = "Average \n Chla \n Depth (m)", 
       size = "Undeveloped \n Area \n %") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(chlaplot1.Late.MN)

chlaplot2.Late.MN <- ggplot() +
  geom_sf(data = states.MN, fill = "white") +
  geom_sf(data = LAGOS.MN.Summary.Late.sf, 
          aes(size = Urban.pct, color = chla.mean),
          alpha = 0.4, show.legend = "point") +
  scale_color_viridis_c(option = "inferno") +
  labs(color = "Average \n Chla \n Depth (m)", 
       size = "Urban \n Area \n %") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(chlaplot2.Late.MN)

chlaplot3.Late.MN <- ggplot() +
  geom_sf(data = states.MN, fill = "white") +
  geom_sf(data = LAGOS.MN.Summary.Late.sf, 
          aes(size = Ag.pct, color = chla.mean),
          alpha = 0.4, show.legend = "point") +
  scale_color_viridis_c(option = "inferno") +
  labs(color = "Average \n Chla \n Depth (m)", 
       size = "Agricultural \n Area \n %") +
  theme(legend.position = "right", legend.text = element_text(size = 7),
        legend.title = element_text(size = 8),
        legend.margin = margin(0,0,0,0)) 
print(secchiplot3.Late.MN)



```



```{r}
LAGOS.MN.processed.Early.sf <- LAGOS.MN.processed.Early.sf %>%
  na.omit()
LAGOS.MN.processed.Prime.sf <- LAGOS.MN.processed.Prime.sf %>%
  na.omit() %>%
  filter(chla > 0)
LAGOS.MN.processed.Late.sf <- LAGOS.MN.processed.Late.sf %>%
  na.omit()

```





```{r}
st_geometry(LAGOS.MN.processed.Early.sf) <- NULL
write.csv(x =  LAGOS.MN.processed.Early.sf, row.names = FALSE,
          file =  "./data/processed/LAGOS.MN.processed.Early.csv")

st_geometry(LAGOS.MN.processed.Prime.sf) <- NULL
write.csv(x =  LAGOS.MN.processed.Prime.sf, row.names = FALSE,
          file =  "./data/processed/LAGOS.MN.processed.Prime.csv")

st_geometry(LAGOS.MN.processed.Late.sf) <- NULL
write.csv(x =  LAGOS.MN.processed.Late.sf, row.names = FALSE,
          file =  "./data/processed/LAGOS.MN.processed.Late.csv")
```






