---
title: "Keith_LAGOS_Exploration"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Questions for the group:
1) Should we combine land use into ag, undeveloped, urban?
2) Can bioregions capture urban land use?

```{r LAGOSNE setup}

#Install packages if necessary

install.packages("LAGOSNE")
install.packages("lubridate")
install.packages("tidyverse")

#load packages
library(tidyverse)
library(lubridate)
library(LAGOSNE)
library(ggplot2)

invisible(lapply(packages, library, character.only = TRUE)) 

theme_set(theme_classic())


#load LAGOS data
#lagosne_get(dest_folder = LAGOSNE:::lagos_path(), overwrite = TRUE)

invisible(lapply(packages, library, character.only = TRUE)) 

LAGOSdata <- lagosne_load()

# creating specific lagos files
LAGOSstate <- LAGOSdata$state
LAGOSlocus <- LAGOSdata$locus
LAGOSnutrient <- LAGOSdata$epi_nutr
LAGOSiwslulc <- LAGOSdata$iws.lulc
LAGOSiws <- LAGOSdata$iws
```

```{r adding a season column}

```


```{r adding a season column}
#we are creating growing seasons; early, prime, late. They will be based off of water temperature and day of year. We choose May 15 and October 1 because these are arbitrary but approximate bookends to the prime growing season.
# Visualization

seasonvisualizationplot <- ggplot(LAGOS.MN.processed, aes(x = DOY, y = chla))+
  geom_point()
print(seasonvisualizationplot)

#Code

LAGOS.MN.processed$EarlyTrue <- LAGOS.MN.processed$DOY < 136 #Before May 15
LAGOS.MN.processed$PrimeTrue <- LAGOS.MN.processed$DOY >=136 & LAGOS.MN.processed$DOY <= 273 #May 15 to September 30
LAGOS.MN.processed$LateTrue <- LAGOS.MN.processed$DOY > 273  #October 1 and later

LAGOS.MN.processed$EarlyTrue <- ifelse(LAGOS.MN.processed$EarlyTrue == TRUE, "Early", "No")
LAGOS.MN.processed$PrimeTrue <- ifelse(LAGOS.MN.processed$PrimeTrue == TRUE, "Prime", "No")
LAGOS.MN.processed$LateTrue <- ifelse(LAGOS.MN.processed$LateTrue == TRUE, "Late", "No")

LAGOS.MN.processed$Season <- LAGOS.MN.processed$EarlyTrue == "Early"
  
LAGOS.MN.processed$Season[LAGOS.MN.processed$EarlyTrue == "Early"] <- "Early"
LAGOS.MN.processed$Season[LAGOS.MN.processed$PrimeTrue == "Prime"] <- "Prime"
LAGOS.MN.processed$Season[LAGOS.MN.processed$LateTrue == "Late"] <- "Late"

LAGOS.MN.processed  <- LAGOS.MN.processed %>%
  select(-c(EarlyTrue, PrimeTrue, LateTrue))
```

